### ISSUE TITLE
State and Reader monads have no type constructor anymore

### ISSUE THREAD

**Issue by schmittlauch** [pvorb/learn-you-a-haskell#43]
the State and Reader monads from the mtl package have been redefined and don't expose their data constructors anymore, see https://stackoverflow.com/questions/24103108/where-is-the-data-constructor-for-state#24103135

Instead state monads are now created using the `state` function.
Reader changed similarly.

**Comment by pvorb** [comment]
I'm not keeping this up to date with changes to Haskell. This was just an export from the original book and I used it to generate an EPUB version of the book. :shrug:
