### ISSUE TITLE
learnyouahaskell.com is down

### ISSUE THREAD

**Issue by smith558** [pvorb/learn-you-a-haskell#46]
![image](https://user-images.githubusercontent.com/44023416/147391371-b234e048-4c68-4e26-b82d-90fa459fe6b2.png)
![image](https://user-images.githubusercontent.com/44023416/147391356-96cc565b-386c-40d4-99be-5c051b164540.png)

**Comment by jschlieber** [comment]
down for me as well... was the page working during the last 5 days?

**Comment by smith558** [comment]
@jschlieber has been down for over a week now. Might be maintenance. Closed the issue because this repo is actually not anyhow related to the http://learnyouahaskell.com/ web.

For http://learnyouahaskell.com/ access in the meantime during the downtime use: [archived version](https://web.archive.org/web/20211214071442/http://learnyouahaskell.com/chapters)

**Comment by jschlieber** [comment]
@smith558 Thanks. I took this as an opportunity to clone this repo and create my own epub version now...
