### ISSUE TITLE
Pictures are not being shown

### ISSUE THREAD

**Issue by orekav** [pvorb/learn-you-a-haskell#48]
Pictures are not being shown in the Markdown files
https://github.com/pvorb/learn-you-a-haskell/blob/master/en/01-introduction.md

The file points to
https://github.com/pvorb/learn-you-a-haskell/raw/master/en/img/bird.png
but the actual link should be
https://github.com/pvorb/learn-you-a-haskell/raw/master/img/bird.png
(without the end)

**Comment by steviejeebies** [comment]
A pull request was made [here](https://github.com/pvorb/learn-you-a-haskell/pull/28) for fixing the GitHub image links, but it seems that the focus of the repo is generating an EPUB/PDF, and this requires the links to be left the way they are. I've made a fork which displays the images on GitHub: https://github.com/steviejeebies/learn-you-a-haskell. I'll try to keep an eye on it and fetch upstream whenever it's needed, but I can't promise anything. 

Also might be worth taking a look at [the alternative Jupyter Notebook version of the book](https://github.com/jamesdbrock/learn-you-a-haskell-notebook), it might suit better than the EPUB/PDF/GitHub format.

**Comment by pvorb** [comment]
@steviejeebies Exactly, thanks for the clarification. And thank you for the link to the Jupyter Notebook. That version looks really cool and helpful. :+1:

If we get a PR that fixes the images on Github without breaking the EPUB and PDF build, I'd definitely merge it.
