### ISSUE TITLE
Code samples don't wrap in epub

### ISSUE THREAD

**Issue by schmittlauch** [pvorb/learn-you-a-haskell#6]
The text of the code samples doesn't wrap and is cut off at the end of the screen.
Tested with:
- Pocketbook Ultra
- FBReader

**Comment by pvorb** [comment]
That's bad. Probably adding

~~~ css
pre {
    white-space: pre-wrap;       /* CSS 3 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
~~~

to the EPUB's stylesheet would fix the problem for you.

You can achieve this by calling pandoc with `--epub-stylesheet=FILE`.

Feel free to leave a pull request, if you succeed.
